export const jobs = [
  { value: "software_engineer", label: "Software Engineer" },
  { value: "frontend_developer", label: "Frontend Developer" },
  { value: "backend_developer", label: "Backend Developer" },
  { value: "fullstack_developer", label: "Full Stack Developer" },
  { value: "data_scientist", label: "Data Scientist" },
  { value: "machine_learning_engineer", label: "Machine Learning Engineer" },
  { value: "devops_engineer", label: "DevOps Engineer" },
  { value: "ui_ux_designer", label: "UI/UX Designer" },
  { value: "product_manager", label: "Product Manager" },
  { value: "qa_engineer", label: "QA Engineer" },
];
export const interviewTypes = [
  { value: "behavioral", label: "Behavioral Interview" },
  { value: "technical", label: "Technical Interview" },
  { value: "case", label: "Case Interview" },
  { value: "panel", label: "Panel Interview" },
  { value: "group", label: "Group Interview" },
  { value: "phone", label: "Phone Interview" },
  { value: "video", label: "Video Interview" },
  { value: "one_on_one", label: "One-on-One Interview" },
  { value: "stress", label: "Stress Interview" },
  { value: "competency", label: "Competency-Based Interview" },
  { value: "coding", label: "Coding Interview" },
  { value: "system_design", label: "System Design Interview" },
  { value: "situational", label: "Situational Interview" },
  { value: "portfolio", label: "Portfolio/Presentation Interview" },
  { value: "hr", label: "HR Interview" },
  { value: "walk_in", label: "Walk-in Interview" },
  { value: "on_site", label: "On-site Interview" },
  { value: "informational", label: "Informational Interview" },
  { value: "exit", label: "Exit Interview" },
];
